class InvalidTopicName(Exception):
    ...

class InvalidGroupId(Exception):
    ...

class SendingError(Exception):
    ...

class ActionError(Exception):
    ...

class TrasnactionPreparingError(ActionError):
    ...
